// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

#nullable disable

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240509115929_AddBasicUsers")]
    partial class AddBasicUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comparisons");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLogin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin");

                    b.ToTable("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeliveryDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDataId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComparisonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FavouritesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInComparison")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInFavourites")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonId");

                    b.HasIndex("FavouritesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f7fafc58-1811-4d18-8356-cd568ee803c8"),
                            Cost = 0m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name0"
                        },
                        new
                        {
                            Id = new Guid("fa6ea92c-9ec8-43f4-9fd5-11fdfb4973af"),
                            Cost = 100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = new Guid("5764666e-4212-48fa-96b8-efb776209b7d"),
                            Cost = 200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name2"
                        },
                        new
                        {
                            Id = new Guid("fe5ca804-bc57-4ec5-a3ed-c7f8f27aad0e"),
                            Cost = 300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name3"
                        },
                        new
                        {
                            Id = new Guid("f8880ffe-1f5b-48bf-adad-347b54cbb131"),
                            Cost = 400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name4"
                        },
                        new
                        {
                            Id = new Guid("7453169e-d79c-4689-9420-06a98d5b8bca"),
                            Cost = 500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name5"
                        },
                        new
                        {
                            Id = new Guid("14d10c52-cbe1-4031-b5cb-e2f39a347153"),
                            Cost = 600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name6"
                        },
                        new
                        {
                            Id = new Guid("e043bb94-ae83-4b69-afec-ba3dd7d767fb"),
                            Cost = 700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name7"
                        },
                        new
                        {
                            Id = new Guid("425b0f08-f505-4ad3-9f94-10681824eae6"),
                            Cost = 800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name8"
                        },
                        new
                        {
                            Id = new Guid("59f20b4a-0735-412a-acb3-d05a302e093c"),
                            Cost = 900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name9"
                        },
                        new
                        {
                            Id = new Guid("d2ac1be1-7887-4c91-827b-1449b3a47a7f"),
                            Cost = 1000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name10"
                        },
                        new
                        {
                            Id = new Guid("f168addd-7f8f-4671-a447-a22fb8013591"),
                            Cost = 1100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name11"
                        },
                        new
                        {
                            Id = new Guid("70da25f7-448d-475c-8b44-aecf07129de4"),
                            Cost = 1200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name12"
                        },
                        new
                        {
                            Id = new Guid("5145b1d7-115d-411a-9a04-48718aed016b"),
                            Cost = 1300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name13"
                        },
                        new
                        {
                            Id = new Guid("0e5b4da1-5628-4f13-a32b-b1b7f1ece6c9"),
                            Cost = 1400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name14"
                        },
                        new
                        {
                            Id = new Guid("8509278e-7df7-4427-94d1-34e75b18e556"),
                            Cost = 1500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name15"
                        },
                        new
                        {
                            Id = new Guid("1cc1e387-77f2-4e7c-ba79-13be2b568da8"),
                            Cost = 1600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name16"
                        },
                        new
                        {
                            Id = new Guid("b5267945-0180-4fb7-8718-97fd3f6c6601"),
                            Cost = 1700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name17"
                        },
                        new
                        {
                            Id = new Guid("d7baa3fe-658d-44bf-ad7a-9c07b7f9c01f"),
                            Cost = 1800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name18"
                        },
                        new
                        {
                            Id = new Guid("be96a883-8437-4bff-8565-342667a8a8bb"),
                            Cost = 1900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name19"
                        },
                        new
                        {
                            Id = new Guid("3de50e20-0527-4d6d-a920-1fe28b6494ec"),
                            Cost = 2000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name20"
                        },
                        new
                        {
                            Id = new Guid("f829762d-53da-41cc-94ee-0d606ab05795"),
                            Cost = 2100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name21"
                        },
                        new
                        {
                            Id = new Guid("a9fef1b3-c7f5-4fd6-8fe0-2b1ddc0d778f"),
                            Cost = 2200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name22"
                        },
                        new
                        {
                            Id = new Guid("91ae481d-e539-4e9a-a3e0-469d9d48ece9"),
                            Cost = 2300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name23"
                        },
                        new
                        {
                            Id = new Guid("3353009c-8de7-4cbc-808a-0268dbaf2cf4"),
                            Cost = 2400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name24"
                        },
                        new
                        {
                            Id = new Guid("2cd88341-3628-4e2a-9118-0a63b181c2ac"),
                            Cost = 2500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name25"
                        },
                        new
                        {
                            Id = new Guid("189ea2ef-1f6d-403c-9b89-734c56e4200b"),
                            Cost = 2600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name26"
                        },
                        new
                        {
                            Id = new Guid("9bfaa4df-4540-4fae-a656-c512ab5b1499"),
                            Cost = 2700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name27"
                        },
                        new
                        {
                            Id = new Guid("34290b4b-45e0-4a9d-ac91-a88516d18178"),
                            Cost = 2800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name28"
                        },
                        new
                        {
                            Id = new Guid("1734013b-7a91-450e-abe3-86967cb90ea6"),
                            Cost = 2900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name29"
                        },
                        new
                        {
                            Id = new Guid("75a2c608-1d27-4161-9f4c-28e2249bc1d0"),
                            Cost = 3000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name30"
                        },
                        new
                        {
                            Id = new Guid("39c882f1-7c78-4c99-9a1a-684601ab44af"),
                            Cost = 3100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name31"
                        },
                        new
                        {
                            Id = new Guid("f4433020-4eac-43c9-95e4-ee7754cfcfe9"),
                            Cost = 3200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name32"
                        },
                        new
                        {
                            Id = new Guid("746ed55e-05d1-46f3-818e-19799709b402"),
                            Cost = 3300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name33"
                        },
                        new
                        {
                            Id = new Guid("214dc587-ac46-4094-b0d8-1b9e41773bc5"),
                            Cost = 3400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name34"
                        },
                        new
                        {
                            Id = new Guid("4f98eba7-9f3f-4ae3-b12c-b5d69c7034f1"),
                            Cost = 3500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name35"
                        },
                        new
                        {
                            Id = new Guid("b481a390-a744-4b66-a34f-d916be857723"),
                            Cost = 3600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name36"
                        },
                        new
                        {
                            Id = new Guid("9f485c28-0034-4349-8c8f-4bb13e5f69bc"),
                            Cost = 3700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name37"
                        },
                        new
                        {
                            Id = new Guid("9cfa5605-3b01-4e67-adc0-90c5061e401d"),
                            Cost = 3800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name38"
                        },
                        new
                        {
                            Id = new Guid("909c2cc7-6ea3-4d40-b693-fc52f8898466"),
                            Cost = 3900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name39"
                        },
                        new
                        {
                            Id = new Guid("f05ce6b6-6f65-4f19-93e6-4f0b55bec3e0"),
                            Cost = 4000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name40"
                        },
                        new
                        {
                            Id = new Guid("a4840c3d-974e-4006-8260-6f36f72346a1"),
                            Cost = 4100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name41"
                        },
                        new
                        {
                            Id = new Guid("6dd86860-5b4a-4922-84ef-912dd01f01d8"),
                            Cost = 4200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name42"
                        },
                        new
                        {
                            Id = new Guid("05d4a10f-8157-4d04-aacb-ed6783d3c1ef"),
                            Cost = 4300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name43"
                        },
                        new
                        {
                            Id = new Guid("729a8ea5-f02f-4fe0-b7ef-cf23c419973f"),
                            Cost = 4400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name44"
                        },
                        new
                        {
                            Id = new Guid("3d8f7cf6-0f21-4131-a893-93e0d6b4161c"),
                            Cost = 4500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name45"
                        },
                        new
                        {
                            Id = new Guid("bb355cf8-44ba-476e-a943-4420e468528c"),
                            Cost = 4600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name46"
                        },
                        new
                        {
                            Id = new Guid("ae86f80b-c078-4d0d-a0d2-1f6ad0808972"),
                            Cost = 4700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name47"
                        },
                        new
                        {
                            Id = new Guid("6df305c6-8d4d-4f37-b216-8d4346d0bbfe"),
                            Cost = 4800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name48"
                        },
                        new
                        {
                            Id = new Guid("34fec9ee-3063-46da-959a-db86c57fd6ac"),
                            Cost = 4900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name49"
                        },
                        new
                        {
                            Id = new Guid("efe3c82e-331f-4d69-9b32-79e1be2b947e"),
                            Cost = 5000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name50"
                        },
                        new
                        {
                            Id = new Guid("9519b474-4cdb-4a8e-a2e0-0f6d0b9b9853"),
                            Cost = 5100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name51"
                        },
                        new
                        {
                            Id = new Guid("be3148e0-746a-4e9b-ae96-7443d1f13e7f"),
                            Cost = 5200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name52"
                        },
                        new
                        {
                            Id = new Guid("f789aeb5-5058-4a8e-8720-c514194ce4f3"),
                            Cost = 5300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name53"
                        },
                        new
                        {
                            Id = new Guid("30f72784-b3b6-4de8-b7f9-8bf5f151295b"),
                            Cost = 5400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name54"
                        },
                        new
                        {
                            Id = new Guid("67cb5eeb-99c6-4ee3-9cae-c271428942e0"),
                            Cost = 5500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name55"
                        },
                        new
                        {
                            Id = new Guid("eb17b146-2ae1-4376-a66c-9ade3188a31b"),
                            Cost = 5600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name56"
                        },
                        new
                        {
                            Id = new Guid("1b4fdea9-a543-4468-9339-288067e1ad03"),
                            Cost = 5700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name57"
                        },
                        new
                        {
                            Id = new Guid("126f668d-1c22-4806-8f0d-e00bac477e6b"),
                            Cost = 5800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name58"
                        },
                        new
                        {
                            Id = new Guid("2f49fc5f-8a11-4778-84d2-17bbeccd1553"),
                            Cost = 5900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name59"
                        },
                        new
                        {
                            Id = new Guid("54e5e444-677c-4ec9-a588-bdce33746d92"),
                            Cost = 6000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name60"
                        },
                        new
                        {
                            Id = new Guid("b9c4036e-ed91-42b8-ae8c-46d6ae85534a"),
                            Cost = 6100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name61"
                        },
                        new
                        {
                            Id = new Guid("2aafdd0f-3fe2-4c0d-b087-60019f49dc02"),
                            Cost = 6200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name62"
                        },
                        new
                        {
                            Id = new Guid("b2db8889-53cf-4d01-8083-fc75e79296a8"),
                            Cost = 6300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name63"
                        },
                        new
                        {
                            Id = new Guid("3aaaa6ca-683b-423b-aab0-c080e8cc57b9"),
                            Cost = 6400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name64"
                        },
                        new
                        {
                            Id = new Guid("05325365-e58a-42a4-9257-bef1d3d2fea7"),
                            Cost = 6500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name65"
                        },
                        new
                        {
                            Id = new Guid("36a670ad-ac6a-4a98-9cea-48610d3f3dba"),
                            Cost = 6600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name66"
                        },
                        new
                        {
                            Id = new Guid("8a1bf9be-f32a-442b-be5c-f65c26f47d77"),
                            Cost = 6700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name67"
                        },
                        new
                        {
                            Id = new Guid("31417907-0c62-436e-a5b7-24fbb449f82d"),
                            Cost = 6800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name68"
                        },
                        new
                        {
                            Id = new Guid("4c4bcfbc-5dc1-4d58-be89-418191a01b47"),
                            Cost = 6900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name69"
                        },
                        new
                        {
                            Id = new Guid("9d3788db-41cd-4f8f-b7b7-71c8d4949d10"),
                            Cost = 7000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name70"
                        },
                        new
                        {
                            Id = new Guid("3e5ffc5a-b267-4b35-b57b-6585cdc8563c"),
                            Cost = 7100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name71"
                        },
                        new
                        {
                            Id = new Guid("186f831c-0aae-4f29-85e6-a2313ddc23c3"),
                            Cost = 7200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name72"
                        },
                        new
                        {
                            Id = new Guid("41eb8835-b59e-46a7-ab5e-5754362069c9"),
                            Cost = 7300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name73"
                        },
                        new
                        {
                            Id = new Guid("3e1c2ed3-af6d-4771-b103-6d7677265cc5"),
                            Cost = 7400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name74"
                        },
                        new
                        {
                            Id = new Guid("2ae4d4ea-c010-46a9-a385-fcc21f0b3efc"),
                            Cost = 7500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name75"
                        },
                        new
                        {
                            Id = new Guid("db65fa95-1d7d-452b-9b2c-b84a2f2b393d"),
                            Cost = 7600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name76"
                        },
                        new
                        {
                            Id = new Guid("f0bda594-aec0-4677-8573-3a58220f7508"),
                            Cost = 7700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name77"
                        },
                        new
                        {
                            Id = new Guid("756f398f-3174-4475-b6b8-f030afa87640"),
                            Cost = 7800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name78"
                        },
                        new
                        {
                            Id = new Guid("f821cbc5-0841-435f-b14c-558532c4b8b6"),
                            Cost = 7900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name79"
                        },
                        new
                        {
                            Id = new Guid("4d5ecc14-9887-414b-91ce-a847aef43509"),
                            Cost = 8000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name80"
                        },
                        new
                        {
                            Id = new Guid("d0dd7cee-21e5-4436-8ca5-ebb96c01a494"),
                            Cost = 8100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name81"
                        },
                        new
                        {
                            Id = new Guid("8647da53-1dfc-434f-98b6-c768937fd6ed"),
                            Cost = 8200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name82"
                        },
                        new
                        {
                            Id = new Guid("d99450ec-0c22-44e1-8f27-b3f1fb133ca2"),
                            Cost = 8300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name83"
                        },
                        new
                        {
                            Id = new Guid("67c74d76-37d0-4677-adb0-bbbaa5b98e75"),
                            Cost = 8400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name84"
                        },
                        new
                        {
                            Id = new Guid("4b510fe8-bcba-4b63-b494-5fa67d3c0c45"),
                            Cost = 8500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name85"
                        },
                        new
                        {
                            Id = new Guid("ad71c416-a662-42c9-a8bb-d0ba9cbb6889"),
                            Cost = 8600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name86"
                        },
                        new
                        {
                            Id = new Guid("60207254-145d-4f86-a119-21ec65b7f251"),
                            Cost = 8700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name87"
                        },
                        new
                        {
                            Id = new Guid("66177840-73c5-4dd4-995b-543437873500"),
                            Cost = 8800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name88"
                        },
                        new
                        {
                            Id = new Guid("a7abc60e-7ea4-4a8c-bfc9-88db539c84dd"),
                            Cost = 8900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name89"
                        },
                        new
                        {
                            Id = new Guid("44205fa1-ca38-460a-b113-c8981acd3f68"),
                            Cost = 9000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name90"
                        },
                        new
                        {
                            Id = new Guid("1aadf54f-e195-46b1-aaed-e6a86b01323c"),
                            Cost = 9100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name91"
                        },
                        new
                        {
                            Id = new Guid("1a1508c0-088a-4aed-bf52-46a05cf995ba"),
                            Cost = 9200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name92"
                        },
                        new
                        {
                            Id = new Guid("77a16df0-b0ff-4396-a891-a8d7be50811e"),
                            Cost = 9300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name93"
                        },
                        new
                        {
                            Id = new Guid("3f4702e6-4f7b-49a8-9357-3e59c3886ccd"),
                            Cost = 9400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name94"
                        },
                        new
                        {
                            Id = new Guid("e1388950-d9b7-476b-8f47-6b1fd8442624"),
                            Cost = 9500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name95"
                        },
                        new
                        {
                            Id = new Guid("45447ec8-57f2-489c-ad6c-5bae2072cd09"),
                            Cost = 9600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name96"
                        },
                        new
                        {
                            Id = new Guid("1d7262bb-855d-4ff6-8c14-26119f5d2ddc"),
                            Cost = 9700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name97"
                        },
                        new
                        {
                            Id = new Guid("43bba197-df20-4e0a-9086-fd087043ec5d"),
                            Cost = 9800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name98"
                        },
                        new
                        {
                            Id = new Guid("dcbca455-bb43-4450-9125-368c63cba15c"),
                            Cost = 9900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name99"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Name = "Administrator"
                        },
                        new
                        {
                            Name = "User"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.HasIndex("RoleName");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Login = "karsanov@mail.ru",
                            Address = "Vatutina 37",
                            Name = "Marat",
                            Password = "marmar",
                            PhoneNumber = "89187080533",
                            RememberMe = false,
                            RoleName = "Administrator",
                            Surname = "Karsanov"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.HasOne("OnlineShop.Db.User", null)
                        .WithMany("DeliveryDatas")
                        .HasForeignKey("UserLogin");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.DeliveryData", "DeliveryData")
                        .WithMany()
                        .HasForeignKey("DeliveryDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Comparison", null)
                        .WithMany("Items")
                        .HasForeignKey("ComparisonId");

                    b.HasOne("OnlineShop.Db.Models.Favourites", null)
                        .WithMany("Items")
                        .HasForeignKey("FavouritesId");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.HasOne("OnlineShop.Db.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Navigation("DeliveryDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
