// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

#nullable disable

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240509115028_AddFirstData")]
    partial class AddFirstData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comparisons");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLogin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin");

                    b.ToTable("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeliveryDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDataId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComparisonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FavouritesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInComparison")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInFavourites")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonId");

                    b.HasIndex("FavouritesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1551d956-8426-47c8-bf45-01cc83914754"),
                            Cost = 0m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name0"
                        },
                        new
                        {
                            Id = new Guid("f34821cd-591b-4b28-8765-a86cd19ef042"),
                            Cost = 100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = new Guid("050b015e-e557-4afe-a91c-375010aed665"),
                            Cost = 200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name2"
                        },
                        new
                        {
                            Id = new Guid("32bd3ec5-45b1-4820-ae6d-d474e1848c65"),
                            Cost = 300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name3"
                        },
                        new
                        {
                            Id = new Guid("da551d68-c07f-4402-baf9-e1e00102fb06"),
                            Cost = 400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name4"
                        },
                        new
                        {
                            Id = new Guid("93f3bc12-243f-4e13-8b3a-c0e14563889a"),
                            Cost = 500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name5"
                        },
                        new
                        {
                            Id = new Guid("99e14540-68f1-44d2-bfd8-a1c864a19d42"),
                            Cost = 600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name6"
                        },
                        new
                        {
                            Id = new Guid("9c4af692-e56c-44f2-8b8f-b5faf4ff2c20"),
                            Cost = 700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name7"
                        },
                        new
                        {
                            Id = new Guid("3436edd5-f7dc-4c86-a81f-08b2c99c82b9"),
                            Cost = 800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name8"
                        },
                        new
                        {
                            Id = new Guid("57b4f572-21b2-4cf8-8844-fc1d91e38014"),
                            Cost = 900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name9"
                        },
                        new
                        {
                            Id = new Guid("4232e07f-8f3e-411e-9b7e-b3b8b63e38f5"),
                            Cost = 1000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name10"
                        },
                        new
                        {
                            Id = new Guid("46d22e79-e4e7-4786-8eb1-5113c8b569ab"),
                            Cost = 1100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name11"
                        },
                        new
                        {
                            Id = new Guid("c8cc6510-daa7-4667-a92b-89c63cb1171c"),
                            Cost = 1200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name12"
                        },
                        new
                        {
                            Id = new Guid("341691b1-f9dc-4d20-a477-88b07abe86f4"),
                            Cost = 1300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name13"
                        },
                        new
                        {
                            Id = new Guid("6bb3fee2-9752-4bd4-ba63-455c6e0d9181"),
                            Cost = 1400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name14"
                        },
                        new
                        {
                            Id = new Guid("7285a46c-2d57-4cc0-952f-07449f4dadec"),
                            Cost = 1500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name15"
                        },
                        new
                        {
                            Id = new Guid("b7d74fe3-055b-4eda-addd-2553f7a1b8ff"),
                            Cost = 1600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name16"
                        },
                        new
                        {
                            Id = new Guid("941b2bb0-fbfd-4b46-972a-0c0c76fe3af5"),
                            Cost = 1700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name17"
                        },
                        new
                        {
                            Id = new Guid("4facd484-4c5d-4722-8ef5-6cf7135c6a7b"),
                            Cost = 1800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name18"
                        },
                        new
                        {
                            Id = new Guid("32ec1f99-3f24-4b9a-8b6f-05a7ec517b37"),
                            Cost = 1900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name19"
                        },
                        new
                        {
                            Id = new Guid("89cbc656-0ab6-45a1-91a9-d0ba3c91c22c"),
                            Cost = 2000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name20"
                        },
                        new
                        {
                            Id = new Guid("94a1a81c-bed8-4480-be1d-78fac69a7a5b"),
                            Cost = 2100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name21"
                        },
                        new
                        {
                            Id = new Guid("9c0fc76b-91e8-4a31-a83e-7bb7aec4522a"),
                            Cost = 2200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name22"
                        },
                        new
                        {
                            Id = new Guid("3bb84bec-3c62-4311-925e-bba0118d4a0e"),
                            Cost = 2300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name23"
                        },
                        new
                        {
                            Id = new Guid("4d478d92-b5bf-47ab-bd71-e1ec99e8c7a6"),
                            Cost = 2400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name24"
                        },
                        new
                        {
                            Id = new Guid("d4a516d8-6929-4cfe-b940-037195ce1a82"),
                            Cost = 2500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name25"
                        },
                        new
                        {
                            Id = new Guid("e70f6985-111d-4d34-819c-468ca5028570"),
                            Cost = 2600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name26"
                        },
                        new
                        {
                            Id = new Guid("2d19858b-baea-4212-9038-1bc154888b2f"),
                            Cost = 2700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name27"
                        },
                        new
                        {
                            Id = new Guid("5dd4ce1f-8612-485e-8676-cd8cbd099040"),
                            Cost = 2800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name28"
                        },
                        new
                        {
                            Id = new Guid("abf4dc6b-4d32-4036-bc55-9179b861b693"),
                            Cost = 2900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name29"
                        },
                        new
                        {
                            Id = new Guid("dc58ed14-f4e2-4e20-96a2-14ff9bb8ab78"),
                            Cost = 3000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name30"
                        },
                        new
                        {
                            Id = new Guid("ff21d764-ba2d-4cf5-a640-f9d300e835dc"),
                            Cost = 3100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name31"
                        },
                        new
                        {
                            Id = new Guid("6023a32f-1328-4be9-bc68-00a63f597a17"),
                            Cost = 3200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name32"
                        },
                        new
                        {
                            Id = new Guid("8eca91d8-0303-4083-9762-ec4160b2b8c4"),
                            Cost = 3300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name33"
                        },
                        new
                        {
                            Id = new Guid("06c6591d-ba20-404a-8c72-8afb61887da7"),
                            Cost = 3400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name34"
                        },
                        new
                        {
                            Id = new Guid("7561be6b-57e8-4321-a780-310a80d9b45a"),
                            Cost = 3500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name35"
                        },
                        new
                        {
                            Id = new Guid("517c15e2-f5d1-4700-b020-c11aa932e9f8"),
                            Cost = 3600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name36"
                        },
                        new
                        {
                            Id = new Guid("92412742-598d-4eba-9fe7-26a841739e42"),
                            Cost = 3700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name37"
                        },
                        new
                        {
                            Id = new Guid("6664cb5e-ab60-4d80-bc9b-e4e4630a7d31"),
                            Cost = 3800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name38"
                        },
                        new
                        {
                            Id = new Guid("96e1255b-4440-487d-9463-f0ce04bd1f8f"),
                            Cost = 3900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name39"
                        },
                        new
                        {
                            Id = new Guid("0ff76584-03f3-42f2-a4f0-1c876f6bd0c0"),
                            Cost = 4000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name40"
                        },
                        new
                        {
                            Id = new Guid("7619090a-4e1d-4996-a5eb-453dc6d70679"),
                            Cost = 4100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name41"
                        },
                        new
                        {
                            Id = new Guid("38ff2633-3b1b-4a4e-9884-c72355922573"),
                            Cost = 4200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name42"
                        },
                        new
                        {
                            Id = new Guid("07826e11-7ce3-4cc9-b8bd-37616b318d60"),
                            Cost = 4300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name43"
                        },
                        new
                        {
                            Id = new Guid("cf74126d-5f0f-493f-8b36-6413f73e21dd"),
                            Cost = 4400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name44"
                        },
                        new
                        {
                            Id = new Guid("6f1c4a7f-ab25-4cf1-b764-e01eff8324ba"),
                            Cost = 4500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name45"
                        },
                        new
                        {
                            Id = new Guid("b4920d1a-9172-46dc-992e-8b63f67db3c0"),
                            Cost = 4600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name46"
                        },
                        new
                        {
                            Id = new Guid("61d2e576-6a49-48f3-b7cd-73e86ba50e64"),
                            Cost = 4700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name47"
                        },
                        new
                        {
                            Id = new Guid("218b79cb-f5de-4544-9ee1-1c7645808ea4"),
                            Cost = 4800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name48"
                        },
                        new
                        {
                            Id = new Guid("7d92c6a9-bd74-43b8-855b-401bc6d8430a"),
                            Cost = 4900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name49"
                        },
                        new
                        {
                            Id = new Guid("a9fb7004-6cb4-47b4-ba8a-12727c0bbb68"),
                            Cost = 5000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name50"
                        },
                        new
                        {
                            Id = new Guid("3fc3b090-1d4f-49af-a85b-624c99e53adf"),
                            Cost = 5100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name51"
                        },
                        new
                        {
                            Id = new Guid("f402298c-465a-441b-b71a-3ae66fcb2649"),
                            Cost = 5200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name52"
                        },
                        new
                        {
                            Id = new Guid("1e682c66-9b4e-4884-bef3-889c1ccd087a"),
                            Cost = 5300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name53"
                        },
                        new
                        {
                            Id = new Guid("0c4e5bbd-6f24-46ea-9c65-e2fb36a03a98"),
                            Cost = 5400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name54"
                        },
                        new
                        {
                            Id = new Guid("7a860da9-1688-40b7-97a7-e0780ab8495c"),
                            Cost = 5500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name55"
                        },
                        new
                        {
                            Id = new Guid("0458d28b-c3fe-48ed-bc79-e5a714b594d3"),
                            Cost = 5600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name56"
                        },
                        new
                        {
                            Id = new Guid("38c3ba56-fdbb-4fcd-b6d8-550a5dab0d3f"),
                            Cost = 5700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name57"
                        },
                        new
                        {
                            Id = new Guid("baf76dba-b268-4877-a22f-793dc008fe57"),
                            Cost = 5800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name58"
                        },
                        new
                        {
                            Id = new Guid("41fed191-1d3d-43ca-9e01-ef145e4feecb"),
                            Cost = 5900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name59"
                        },
                        new
                        {
                            Id = new Guid("cf396d7e-1d62-4335-9fad-db0f42964d2a"),
                            Cost = 6000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name60"
                        },
                        new
                        {
                            Id = new Guid("4caaed6c-8d70-4d6c-b31e-066c2584f98a"),
                            Cost = 6100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name61"
                        },
                        new
                        {
                            Id = new Guid("1a0f3dd1-67f7-465e-bdea-449be7cc146b"),
                            Cost = 6200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name62"
                        },
                        new
                        {
                            Id = new Guid("020ee465-ebcb-4fd4-8e8b-84a69cf4ddbe"),
                            Cost = 6300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name63"
                        },
                        new
                        {
                            Id = new Guid("caa1b394-812f-490b-b86d-07398cf3bdde"),
                            Cost = 6400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name64"
                        },
                        new
                        {
                            Id = new Guid("6e317fc0-e620-4aa9-b6e3-9512380d690d"),
                            Cost = 6500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name65"
                        },
                        new
                        {
                            Id = new Guid("9d9a53de-c836-47d3-926c-778c798b24a7"),
                            Cost = 6600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name66"
                        },
                        new
                        {
                            Id = new Guid("654915d2-1420-4b3d-8b57-98b9623e04d9"),
                            Cost = 6700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name67"
                        },
                        new
                        {
                            Id = new Guid("4ff18dae-7eed-4a7e-aafd-874ec6b1cd12"),
                            Cost = 6800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name68"
                        },
                        new
                        {
                            Id = new Guid("782d0042-46bd-45e7-9eae-1e2e64cb9360"),
                            Cost = 6900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name69"
                        },
                        new
                        {
                            Id = new Guid("80a7326e-8f94-4dad-b766-075d7758d31f"),
                            Cost = 7000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name70"
                        },
                        new
                        {
                            Id = new Guid("d27b9bbf-6529-4104-846d-8fbe9ec088d3"),
                            Cost = 7100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name71"
                        },
                        new
                        {
                            Id = new Guid("67ea9e0b-2372-44e6-a287-2c60b759951c"),
                            Cost = 7200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name72"
                        },
                        new
                        {
                            Id = new Guid("a0b0b061-5a23-491f-995a-006642ecab01"),
                            Cost = 7300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name73"
                        },
                        new
                        {
                            Id = new Guid("7a0ce445-1b3e-435c-a867-f8f8365875f7"),
                            Cost = 7400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name74"
                        },
                        new
                        {
                            Id = new Guid("a11cc316-68df-4197-ac2e-4e38729bda16"),
                            Cost = 7500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name75"
                        },
                        new
                        {
                            Id = new Guid("4d475bf5-3f0c-45ed-9a19-d141ac11aba5"),
                            Cost = 7600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name76"
                        },
                        new
                        {
                            Id = new Guid("1b09ddb7-e476-4fac-9c71-fd2b948d1df2"),
                            Cost = 7700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name77"
                        },
                        new
                        {
                            Id = new Guid("d2fa8058-5990-4499-9e59-edfc13b4594e"),
                            Cost = 7800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name78"
                        },
                        new
                        {
                            Id = new Guid("e081fc59-2bb6-4dc4-b5f0-18a0c6212ef0"),
                            Cost = 7900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name79"
                        },
                        new
                        {
                            Id = new Guid("fd0b990c-f173-42fc-9f12-46079ee88876"),
                            Cost = 8000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name80"
                        },
                        new
                        {
                            Id = new Guid("0683aa36-ab01-4e98-bed4-2176f468292f"),
                            Cost = 8100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name81"
                        },
                        new
                        {
                            Id = new Guid("9cb6cd30-5d3e-4b49-a03a-ff167ae9db23"),
                            Cost = 8200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name82"
                        },
                        new
                        {
                            Id = new Guid("5d58cc18-55d1-4754-b5c0-5f90fa35653c"),
                            Cost = 8300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name83"
                        },
                        new
                        {
                            Id = new Guid("b51f94ca-62c6-4524-be86-d574c5be3a4d"),
                            Cost = 8400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name84"
                        },
                        new
                        {
                            Id = new Guid("b633a560-3a1a-4a07-85a0-96452dba3be3"),
                            Cost = 8500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name85"
                        },
                        new
                        {
                            Id = new Guid("eaea7c5e-a493-40ac-86d7-33f99808d2cd"),
                            Cost = 8600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name86"
                        },
                        new
                        {
                            Id = new Guid("a079052d-1cb4-42a7-8fc5-675c0e6ae991"),
                            Cost = 8700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name87"
                        },
                        new
                        {
                            Id = new Guid("d25ee23a-1350-4d15-a04e-98f5128415df"),
                            Cost = 8800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name88"
                        },
                        new
                        {
                            Id = new Guid("98c6ae8a-1d08-4b27-b361-c91ba5920a42"),
                            Cost = 8900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name89"
                        },
                        new
                        {
                            Id = new Guid("e7db8eb0-d373-429d-85f5-a7a7efa9db67"),
                            Cost = 9000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name90"
                        },
                        new
                        {
                            Id = new Guid("fb1ba2f7-d384-4b30-b727-9760b3f7ee31"),
                            Cost = 9100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name91"
                        },
                        new
                        {
                            Id = new Guid("0d49521f-0b3b-41fc-804d-d7b1b596e563"),
                            Cost = 9200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name92"
                        },
                        new
                        {
                            Id = new Guid("71590f62-edfe-493b-bb9d-738ddb3bb966"),
                            Cost = 9300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name93"
                        },
                        new
                        {
                            Id = new Guid("db2ec1a7-6ba1-483f-85b2-9c3c1351b9d8"),
                            Cost = 9400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name94"
                        },
                        new
                        {
                            Id = new Guid("84471332-7522-496f-8b4e-15ea9c3e649c"),
                            Cost = 9500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name95"
                        },
                        new
                        {
                            Id = new Guid("6d53413e-5538-48b1-8a18-01d302724c13"),
                            Cost = 9600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name96"
                        },
                        new
                        {
                            Id = new Guid("2adaf171-50a5-43ab-bf0f-53cf0ac460f9"),
                            Cost = 9700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name97"
                        },
                        new
                        {
                            Id = new Guid("41fd53b2-d9b0-445a-9c58-16e327d20138"),
                            Cost = 9800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name98"
                        },
                        new
                        {
                            Id = new Guid("64f38adb-3bbd-4041-85c3-7a5701acd0c7"),
                            Cost = 9900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name99"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Name = "Administrator"
                        },
                        new
                        {
                            Name = "User"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.HasIndex("RoleName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.HasOne("OnlineShop.Db.User", null)
                        .WithMany("DeliveryDatas")
                        .HasForeignKey("UserLogin");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.DeliveryData", "DeliveryData")
                        .WithMany()
                        .HasForeignKey("DeliveryDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Comparison", null)
                        .WithMany("Items")
                        .HasForeignKey("ComparisonId");

                    b.HasOne("OnlineShop.Db.Models.Favourites", null)
                        .WithMany("Items")
                        .HasForeignKey("FavouritesId");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.HasOne("OnlineShop.Db.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Navigation("DeliveryDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
