// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineShop.Db;

#nullable disable

namespace OnlineShop.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240503153636_AddFirstData")]
    partial class AddFirstData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<Guid?>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Comparisons");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLogin")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserLogin");

                    b.ToTable("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Favourites");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeliveryDataId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDataId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ComparisonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FavouritesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInComparison")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInFavourites")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ComparisonId");

                    b.HasIndex("FavouritesId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f53b2ad3-4b36-499f-b541-34acb6d52efc"),
                            Cost = 0m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name0"
                        },
                        new
                        {
                            Id = new Guid("247e7349-e03d-4c89-b680-5199e8aa3286"),
                            Cost = 100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name1"
                        },
                        new
                        {
                            Id = new Guid("1b62a685-1687-4721-92b8-59feb13119ed"),
                            Cost = 200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name2"
                        },
                        new
                        {
                            Id = new Guid("7dc65c0a-15ea-45e1-a448-808218949257"),
                            Cost = 300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name3"
                        },
                        new
                        {
                            Id = new Guid("5911f8a2-be2d-43f0-a1b5-3d41f72822f2"),
                            Cost = 400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name4"
                        },
                        new
                        {
                            Id = new Guid("0fa8734b-25b9-456c-be3d-d1c147bdcdb2"),
                            Cost = 500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name5"
                        },
                        new
                        {
                            Id = new Guid("eb53c021-cd2e-4235-bfeb-67827bf16111"),
                            Cost = 600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name6"
                        },
                        new
                        {
                            Id = new Guid("ca9e436d-2b15-4ea0-ad1f-dca3aeccbf90"),
                            Cost = 700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name7"
                        },
                        new
                        {
                            Id = new Guid("5a18097a-6517-4907-b9e0-8886b14caa68"),
                            Cost = 800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name8"
                        },
                        new
                        {
                            Id = new Guid("571d09da-6d2f-493b-b79e-6d137bfe9ab0"),
                            Cost = 900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name9"
                        },
                        new
                        {
                            Id = new Guid("88b19c94-5945-4050-8111-a4a063998b9b"),
                            Cost = 1000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name10"
                        },
                        new
                        {
                            Id = new Guid("53d01021-3ed1-4b56-8f85-3112a02141df"),
                            Cost = 1100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name11"
                        },
                        new
                        {
                            Id = new Guid("973bdaa6-da5e-4ead-8e83-75f624f75ec5"),
                            Cost = 1200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name12"
                        },
                        new
                        {
                            Id = new Guid("bfcdc284-605d-4a19-90f9-2212a696e9f1"),
                            Cost = 1300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name13"
                        },
                        new
                        {
                            Id = new Guid("3a664fb8-fc86-4b69-b096-04b9fcfe3e6d"),
                            Cost = 1400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name14"
                        },
                        new
                        {
                            Id = new Guid("ecbf9abf-f23e-49e5-a763-d8f257bdee91"),
                            Cost = 1500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name15"
                        },
                        new
                        {
                            Id = new Guid("0c88a881-5fbd-4910-88d8-0b2482b651db"),
                            Cost = 1600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name16"
                        },
                        new
                        {
                            Id = new Guid("41da35f2-83a9-4ad1-92fb-a181df753229"),
                            Cost = 1700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name17"
                        },
                        new
                        {
                            Id = new Guid("943bc3f6-c69b-4e30-be3b-a2adb5e66380"),
                            Cost = 1800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name18"
                        },
                        new
                        {
                            Id = new Guid("d30d1238-c2dd-48b5-8d1c-7dca5c278091"),
                            Cost = 1900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name19"
                        },
                        new
                        {
                            Id = new Guid("ad0146c2-7892-45f9-850c-ff6dd09dcb55"),
                            Cost = 2000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name20"
                        },
                        new
                        {
                            Id = new Guid("901766e2-bdbb-43dd-a7f6-43046c3806a4"),
                            Cost = 2100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name21"
                        },
                        new
                        {
                            Id = new Guid("c1cb0f00-da9a-4e2a-8cfe-bdef329bb955"),
                            Cost = 2200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name22"
                        },
                        new
                        {
                            Id = new Guid("19b76339-d173-4240-8b46-b0da5f6f6a04"),
                            Cost = 2300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name23"
                        },
                        new
                        {
                            Id = new Guid("6909ac94-2036-41ed-927f-6406224bade6"),
                            Cost = 2400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name24"
                        },
                        new
                        {
                            Id = new Guid("786174d5-70c1-4223-a13c-db7281acd1ee"),
                            Cost = 2500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name25"
                        },
                        new
                        {
                            Id = new Guid("cdead5c4-4b6a-40e5-9b60-ec70813847f4"),
                            Cost = 2600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name26"
                        },
                        new
                        {
                            Id = new Guid("6aeebbc1-0338-4fbc-934b-fa58ba158bde"),
                            Cost = 2700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name27"
                        },
                        new
                        {
                            Id = new Guid("7beed880-34dc-4d41-addb-0a0d8b5430dc"),
                            Cost = 2800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name28"
                        },
                        new
                        {
                            Id = new Guid("33472187-23ad-4308-b523-c9242eeb21ce"),
                            Cost = 2900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name29"
                        },
                        new
                        {
                            Id = new Guid("e605968d-ca69-4cc3-bacb-631789e09c31"),
                            Cost = 3000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name30"
                        },
                        new
                        {
                            Id = new Guid("76a343dd-92e9-48af-baa0-5b8d08a48e84"),
                            Cost = 3100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name31"
                        },
                        new
                        {
                            Id = new Guid("746b1a71-f793-40e2-98a5-f4b935c9cefd"),
                            Cost = 3200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name32"
                        },
                        new
                        {
                            Id = new Guid("d4270b06-02f1-4f61-9f59-21414aaa7f03"),
                            Cost = 3300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name33"
                        },
                        new
                        {
                            Id = new Guid("01fba458-755e-4839-a559-a711adc59528"),
                            Cost = 3400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name34"
                        },
                        new
                        {
                            Id = new Guid("1fc404ef-dbf6-459f-bdae-adea19ed4187"),
                            Cost = 3500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name35"
                        },
                        new
                        {
                            Id = new Guid("36b32d25-5565-4a20-959b-5f42ae2231b7"),
                            Cost = 3600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name36"
                        },
                        new
                        {
                            Id = new Guid("7d2f72fb-5e27-495b-89f8-9159ed139623"),
                            Cost = 3700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name37"
                        },
                        new
                        {
                            Id = new Guid("f1997bfb-3422-4b6a-9a7b-bc94b208e202"),
                            Cost = 3800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name38"
                        },
                        new
                        {
                            Id = new Guid("141370de-0dea-42b7-94fa-96f5e77880d6"),
                            Cost = 3900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name39"
                        },
                        new
                        {
                            Id = new Guid("8af7f3d3-1af3-419c-b887-7159e41532de"),
                            Cost = 4000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name40"
                        },
                        new
                        {
                            Id = new Guid("928a997b-af78-4634-8be9-8b203083ec5e"),
                            Cost = 4100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name41"
                        },
                        new
                        {
                            Id = new Guid("02184905-10c6-4830-a4d0-4d6e3b7fc644"),
                            Cost = 4200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name42"
                        },
                        new
                        {
                            Id = new Guid("5333831f-0c07-43ae-8ec5-1d098ae4c3f7"),
                            Cost = 4300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name43"
                        },
                        new
                        {
                            Id = new Guid("105ffbe5-6938-447d-8932-55b9f087d89c"),
                            Cost = 4400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name44"
                        },
                        new
                        {
                            Id = new Guid("f4fc5700-bcf3-454d-b499-d6afed89ba4c"),
                            Cost = 4500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name45"
                        },
                        new
                        {
                            Id = new Guid("7796ce58-6073-4310-908c-243054bcd5ce"),
                            Cost = 4600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name46"
                        },
                        new
                        {
                            Id = new Guid("86b8d4f5-5ca9-4b6f-b64e-fd9bcafc02ea"),
                            Cost = 4700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name47"
                        },
                        new
                        {
                            Id = new Guid("b697730a-886a-4801-a68e-845bdfd6b969"),
                            Cost = 4800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name48"
                        },
                        new
                        {
                            Id = new Guid("93cafc22-f80a-4685-970f-3be33a630197"),
                            Cost = 4900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name49"
                        },
                        new
                        {
                            Id = new Guid("54c47ce9-0666-4fbd-848d-bd367127bfcb"),
                            Cost = 5000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name50"
                        },
                        new
                        {
                            Id = new Guid("87d0c5e2-89fb-4d64-8764-e2e5421b861e"),
                            Cost = 5100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name51"
                        },
                        new
                        {
                            Id = new Guid("cbdc98b3-8c07-4982-8aee-31922c75600d"),
                            Cost = 5200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name52"
                        },
                        new
                        {
                            Id = new Guid("7e6afdb1-c822-4dbb-a644-0c673d6492c7"),
                            Cost = 5300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name53"
                        },
                        new
                        {
                            Id = new Guid("dc09221e-ed43-4171-a28d-c97427569832"),
                            Cost = 5400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name54"
                        },
                        new
                        {
                            Id = new Guid("93248196-9306-43c7-9e9f-b5c627079fd3"),
                            Cost = 5500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name55"
                        },
                        new
                        {
                            Id = new Guid("0a99ea39-28b9-4121-a0f8-c0da2fdb6b14"),
                            Cost = 5600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name56"
                        },
                        new
                        {
                            Id = new Guid("6bffd4f9-3131-4591-b17c-c46363608acb"),
                            Cost = 5700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name57"
                        },
                        new
                        {
                            Id = new Guid("e88d279a-3db7-4c25-9320-97779df110ed"),
                            Cost = 5800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name58"
                        },
                        new
                        {
                            Id = new Guid("2a9fa0ab-ec44-47c2-8b5a-16993582613d"),
                            Cost = 5900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name59"
                        },
                        new
                        {
                            Id = new Guid("603fd36b-7d1d-4b7a-abdd-aabc426b99f9"),
                            Cost = 6000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name60"
                        },
                        new
                        {
                            Id = new Guid("88a9df97-ef89-4659-aec2-2f332546d59b"),
                            Cost = 6100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name61"
                        },
                        new
                        {
                            Id = new Guid("0341c423-ceb6-4288-89a6-b989ec413e11"),
                            Cost = 6200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name62"
                        },
                        new
                        {
                            Id = new Guid("9f2f99f7-384c-4e9b-97c3-5707104fe2fc"),
                            Cost = 6300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name63"
                        },
                        new
                        {
                            Id = new Guid("34d450d5-038c-4ed6-b527-8ea380b1d90f"),
                            Cost = 6400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name64"
                        },
                        new
                        {
                            Id = new Guid("baa88f6d-b8be-45e8-b818-a4f750ad3ce6"),
                            Cost = 6500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name65"
                        },
                        new
                        {
                            Id = new Guid("2446ae26-0bbf-4dd4-a629-b07a0c94bee6"),
                            Cost = 6600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name66"
                        },
                        new
                        {
                            Id = new Guid("f5d19160-a35b-40b2-875e-fdd27ddd2e64"),
                            Cost = 6700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name67"
                        },
                        new
                        {
                            Id = new Guid("05899858-f220-4e5c-9716-ae0352a7536c"),
                            Cost = 6800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name68"
                        },
                        new
                        {
                            Id = new Guid("db188e0b-3e31-4ad8-87a2-bb370d528d9d"),
                            Cost = 6900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name69"
                        },
                        new
                        {
                            Id = new Guid("620f911a-6360-4e37-9987-792639178ae9"),
                            Cost = 7000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name70"
                        },
                        new
                        {
                            Id = new Guid("5a9f014f-a0e0-4ea1-bbfb-15437069154c"),
                            Cost = 7100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name71"
                        },
                        new
                        {
                            Id = new Guid("44033022-5967-4546-97cf-a8f83c577950"),
                            Cost = 7200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name72"
                        },
                        new
                        {
                            Id = new Guid("a23d8916-65e8-4aa5-87e0-ad1b2c2d0d52"),
                            Cost = 7300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name73"
                        },
                        new
                        {
                            Id = new Guid("478284bf-b12f-4fce-9f3e-6e65eafae10a"),
                            Cost = 7400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name74"
                        },
                        new
                        {
                            Id = new Guid("5e86c253-322e-43ca-bd19-79575c014f14"),
                            Cost = 7500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name75"
                        },
                        new
                        {
                            Id = new Guid("b94671ab-d07b-487f-be7b-7aac473017df"),
                            Cost = 7600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name76"
                        },
                        new
                        {
                            Id = new Guid("c878ec42-5448-4e4e-8108-9398e658059e"),
                            Cost = 7700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name77"
                        },
                        new
                        {
                            Id = new Guid("a185e8d1-3bbf-4438-8b2f-241f5a0e48a5"),
                            Cost = 7800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name78"
                        },
                        new
                        {
                            Id = new Guid("edbf94be-9add-4afb-bc92-f6eb0ea8410c"),
                            Cost = 7900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name79"
                        },
                        new
                        {
                            Id = new Guid("ee161f74-bb51-494e-ba58-aaf72dd548ca"),
                            Cost = 8000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name80"
                        },
                        new
                        {
                            Id = new Guid("30692f39-d8ef-4979-a27d-f43d2c995503"),
                            Cost = 8100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name81"
                        },
                        new
                        {
                            Id = new Guid("c1899ec1-fdf6-4243-9fe4-faebad848845"),
                            Cost = 8200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name82"
                        },
                        new
                        {
                            Id = new Guid("f5d8a75a-4fff-4c8f-ac33-b873c084b0d6"),
                            Cost = 8300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name83"
                        },
                        new
                        {
                            Id = new Guid("00c5d5df-1558-4e91-80a1-a8e3198d9ba4"),
                            Cost = 8400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name84"
                        },
                        new
                        {
                            Id = new Guid("0ca602d7-f87b-4708-854b-cfe4a84c3c23"),
                            Cost = 8500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name85"
                        },
                        new
                        {
                            Id = new Guid("f1d687fe-5155-4b03-bb93-f4e81d701494"),
                            Cost = 8600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name86"
                        },
                        new
                        {
                            Id = new Guid("7110c3cb-4e7e-4c49-a06f-c89f052a51e7"),
                            Cost = 8700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name87"
                        },
                        new
                        {
                            Id = new Guid("814de527-e838-4e55-b3b1-baaef5d99b9f"),
                            Cost = 8800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name88"
                        },
                        new
                        {
                            Id = new Guid("d8d62579-f1c2-4c2e-8e16-65b844c975fc"),
                            Cost = 8900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name89"
                        },
                        new
                        {
                            Id = new Guid("dd25733e-6b1a-43c2-be83-fb7b70264590"),
                            Cost = 9000m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name90"
                        },
                        new
                        {
                            Id = new Guid("12518a4a-825d-47a3-9abd-cbeca85afa9e"),
                            Cost = 9100m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name91"
                        },
                        new
                        {
                            Id = new Guid("25614a32-551f-4d27-8c71-492a954577c6"),
                            Cost = 9200m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name92"
                        },
                        new
                        {
                            Id = new Guid("67cf7a1a-f678-4dce-abd5-9f5afb395389"),
                            Cost = 9300m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name93"
                        },
                        new
                        {
                            Id = new Guid("9aef0c97-f878-4a4e-a299-1017be828f15"),
                            Cost = 9400m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name94"
                        },
                        new
                        {
                            Id = new Guid("33a338b5-68b4-4e8b-b872-9a2e11de4a32"),
                            Cost = 9500m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name95"
                        },
                        new
                        {
                            Id = new Guid("08dc8629-e526-43c6-9f42-3d15bd073ce2"),
                            Cost = 9600m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name96"
                        },
                        new
                        {
                            Id = new Guid("357b726e-a80c-4fa2-a9bc-c3109a7e4eee"),
                            Cost = 9700m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name97"
                        },
                        new
                        {
                            Id = new Guid("33b0ffd6-9d07-4bbb-bd2c-d6c633904aa2"),
                            Cost = 9800m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name98"
                        },
                        new
                        {
                            Id = new Guid("b36f624a-b346-43ff-966e-e47877ba5a58"),
                            Cost = 9900m,
                            Description = "Very good product!",
                            ImageLink = "/images/DefaultImg.jpg",
                            IsInComparison = false,
                            IsInFavourites = false,
                            Name = "Name99"
                        });
                });

            modelBuilder.Entity("OnlineShop.Db.Role", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Property<string>("Login")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RememberMe")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Login");

                    b.HasIndex("RoleName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.CartItem", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Cart", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineShop.Db.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId");

                    b.HasOne("OnlineShop.Db.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.DeliveryData", b =>
                {
                    b.HasOne("OnlineShop.Db.User", null)
                        .WithMany("DeliveryDatas")
                        .HasForeignKey("UserLogin");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.DeliveryData", "DeliveryData")
                        .WithMany()
                        .HasForeignKey("DeliveryDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryData");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Product", b =>
                {
                    b.HasOne("OnlineShop.Db.Models.Comparison", null)
                        .WithMany("Items")
                        .HasForeignKey("ComparisonId");

                    b.HasOne("OnlineShop.Db.Models.Favourites", null)
                        .WithMany("Items")
                        .HasForeignKey("FavouritesId");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.HasOne("OnlineShop.Db.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleName");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Cart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Comparison", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Favourites", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.Models.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("OnlineShop.Db.User", b =>
                {
                    b.Navigation("DeliveryDatas");
                });
#pragma warning restore 612, 618
        }
    }
}
