version: '3.4'
networks:
  onlineshop:
    driver: bridge
services:
  postgre:
    container_name: online_shop_app_db
    image: postgres:latest
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1Secure*Password1
      POSTGRES_DB: online_shop_karsanov
    ports:
      - 5432:5432
    networks:
      - onlineshop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    
  onlineshopwebapp:
    container_name: online_shop_app_mvc
    image: ${DOCKER_REGISTRY-}onlineshopwebapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - postgre   
      - redis
    restart: unless-stopped 
    networks:
      - onlineshop

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379
    restart: unless-stopped 
    networks:
      - onlineshop

  mssqlserver:
    container_name: reviews_db
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment: 
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1Secure*Password1
    ports:
      - 1433:1433
    networks:
      - onlineshop
    
  reviews_api:
    container_name: reviews_api
    image: ${DOCKER_REGISTRY-}reviewswebapplication
    build:
      context: .
      dockerfile: C:\Users\79187\source\repos\Reviews\Dockerfile
    ports:
      - 80:80
    depends_on:
      - mssqlserver   
    restart: unless-stopped 
    networks:
      - onlineshop

volumes:
  postgres-data: